// src/components/header/header.tsx
import { component$, useSignal, useStylesScoped$ } from "@builder.io/qwik";
import { useLocation, useNavigate } from "@builder.io/qwik-city";
import { ROUTES } from "~/constants/routes";
import { DonutIcon } from "~/components/icons/donut";
import styles from "./header.scss?inline";

export default component$(() => {
  useStylesScoped$(styles);
  const { pathname } = useLocation();
  const isOpen = useSignal(false);
  const navigation = useNavigate();

  return (
    <header>
      <button
        onClick$={() => (isOpen.value = !isOpen.value)}
        class="navigation-menu-button"
      >
        <DonutIcon />
        <DonutIcon />
        <DonutIcon />
      </button>

      {isOpen.value === true && (
        <>
          <div class="navigation-menu">
            <div class="navigation-menu-links">
              {ROUTES.map(({ key, name, path }, index) => (
                <a
                  preventdefault:click
                  onClick$={() => {
                    isOpen.value = false;
                    navigation.path = path;
                  }}
                  key={key}
                  href={path}
                  class={
                    pathname === path
                      ? "navigation-menu-link-active"
                      : "navigation-menu-link"
                  }
                >
                  <p class="navigation-menu-link-p">{name}</p>
                  <div>
                    <small class="navigation-menu-link-small">
                      {index + 1}
                    </small>
                  </div>
                </a>
              ))}
            </div>
          </div>

          <div onClick$={() => (isOpen.value = false)} class="blur-effect" />
        </>
      )}

      <div class="current-page">
        <div class="current-page-title-wrapper">
          <h3 class="current-page-title">{pathname.replaceAll("/", "")}</h3>
        </div>
      </div>
    </header>
  );
});

// components/Header.vue
<template>
  <header>
    <button class="navigation-menu-button" @click="() => (isOpen = !isOpen)">
      <DonutIcon />
      <DonutIcon />
      <DonutIcon />
    </button>

    <div v-if="isOpen === true" class="navigation-menu">
      <div class="navigation-menu-links">
        <a
          v-for="({ key, name, path }, index) in ROUTES"
          :key="key"
          :class="['navigation-menu-link', matchRoute(path) === true && 'navigation-menu-link-active']"
          @click="() => onLinkClick(path)"
        >
          <p class="navigation-menu-link-p">{{ name }}</p>
          <div>
            <small class="navigation-menu-link-small"> {{ index + 1 }} </small>
          </div>
        </a>
      </div>
    </div>

    <div v-if="isOpen === true" class="blur-effect" @click="() => (isOpen = false)" />

    <div class="current-page">
      <div class="current-page-title-wrapper">
        <h3 class="current-page-title">
          {{ navigationTitle }}
        </h3>
      </div>
    </div>
  </header>
</template>

<script setup lang="ts">
import { ROUTES, HOME_ROUTE, PROJECTS_ROUTE } from '~~/constants/routes'

const route = useRoute()
const router = useRouter()
const isOpen = ref(false)

const navigationTitle = computed(() => {
  const matched = ROUTES.find((ROUTE) => ROUTE.path === route.path)
  if (matched) return matched.name
  return ''
})

const matchRoute = (path) => {
  if (path === route.path) return true
  if (path !== HOME_ROUTE.path && route.path.includes(path)) return true
  return false
}

const onLinkClick = (path) => {
  isOpen.value = false
  router.push(path)
}
</script>
